# Site settings
title: Antonio Vida
description: 'Business Card Page'
company_name: 
company_url: 
url: 'http://antoniovida.xyz'
baseurl: ''
profilepic: '/images/antonio.jpg'
bkimage: '/images/bk2.jpg'
google_analytics: UA-XXXXXX-X
mode: dark # default theme "dark" | "light"

author:
  name: 'Antonio Vida'
  email: antoniovlx gmail.com
  twitter_username: anvidaluc
  #  facebook_username:
  github_username:  antoniovlx
  linkedin_username:  antoniovida
  stackoverflow_username: 3713193
  meetup_name:

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

# Collection setting
collections:
  posts:
    output: true

sass:
    # sass_dir: _sass
    style: compressed
    
# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false
  
# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
